### ISSUE TITLE
软件提示弹窗不显示问题

### ISSUE THREAD

**Issue by Smi1eSEC** [UserZYF/blue-dog#2]
非常喜欢老哥的这个主题，不过在使用过程中发现软件的弹窗提示只有一个对勾，看不到提示内容，比如点击软件更新功能。请问能修复一下这个bug吗

**Comment by Smi1eSEC** [comment]
<img width="503" alt="image" src="https://user-images.githubusercontent.com/39610144/182849509-c84fe0d8-b4f3-4bcc-a8e1-17d02d9f8719.png">

**Comment by UserZYF** [comment]
朋友忙着找工作，得耽搁一阵



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年8月4日(周四) 晚上8:36
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [UserZYF/blue-dog] 软件提示弹窗不显示问题 (Issue #2)




 
非常喜欢老哥的这个主题，不过在使用过程中发现软件的弹窗提示只有一个对勾，看不到提示内容，比如点击软件更新功能。请问能修复一下这个bug吗
